//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Capow32.rc
//
#define RAMP_NO_PARAM                   0
#define CA_ZAP                          0
#define CA1_2                           0
#define ID_TOOLBAR                      1
#define RAMP_VEL_MULT                   1
#define CA_CLONE                        1
#define CA1_4                           1
#define RAMP_ACCEL                      2
#define CA_SEX                          2
#define CA1_8                           2
#define RAMP_MAX_VEL                    3
#define CA1_16                          3
#define RAMP_MAX_INTENSITY              4
#define CA2_2                           4
#define RAMP_HEAT_COUNT                 5
#define CA2_4                           5
#define RAMP_LAMBDA                     6
#define CA3_2                           6
#define RAMP_BAND                       7
#define CA3_4                           7
#define RAMP_FRICTION                   8
#define CA4_2                           8
#define RAMP_SPRING                     9
#define CA5_2                           9
#define RAMP_DRIVER_AMP                 10
#define CA6_2                           10
#define CA_STANDARD                     10
#define RAMP_DRIVER_FREQ                11
#define CA1_256                         11
#define CA_REVERSIBLE                   11
#define RAMP_INDUCTANCE                 12
#define CA_WAVE                         12
#define IDC_ENTROPY_SCORE               13
#define CA_WAVE2                        13
#define IDC_ENTROPY                     14
#define CA_HEATWAVE                     14
#define CA_OSCILLATOR                   15
#define CA_USER                         16
#define CA_DIVERSE_OSCILLATOR           17
#define CA_DIVERSE_OSCILLATOR_WAVE      18
#define CA_ULAM_WAVE                    19
#define CA_AUTO_ULAM_WAVE               20
#define ALT_CA_WAVE                     21
#define ALT_CA_WAVE2                    22
#define ALT_CA_OSCILLATOR               23
#define IDC_COLRAMP                     24
#define IDC_VSCROLL1                    24
#define ALT_CA_OSCILLATOR_WAVE          24
#define ALT_CA_DIVERSE_OSCILLATOR       25
#define ALT_CA_DIVERSE_OSCILLATOR_WAVE  26
#define ALT_CA_ULAM_WAVE                27
#define CA_CUBIC_ULAM_WAVE              28
#define CA_HEATWAVE2                    29
#define CA_WAVE_2D                      30
#define CA_HEAT_2D                      31
#define IDC_REVERSE                     39
#define IDC_SINESEED                    40
#define IDC_SYM                         41
#define IDC_AUTOSMOOTH                  41
#define IDC_ONESEED                     42
#define IDC_COPYMUTATE                  43
#define IDC_BREED                       44
#define IDC_SHRINK                      45
#define IDC_EXPAND                      46
#define IDC_RANDOMSEED                  47
#define IDC_SMOOTH                      48
#define IDC_FOURIERSEED                 49
#define IDM_PARAMS                      50
#define IDM_ZAP                         51
#define IDM_CYCLE                       52
#define IDM_TIMER                       53
#define IDM_COLOR                       53
#define IDM_LOOKUP                      54
#define IDM_INFO                        55
#define IDM_CONTROLS                    56
#define IDC_RAND_COLOR                  60
#define IDC_RAND_LOOKUP                 61
#define IDC_MUTATE                      62
#define IDM_EXIT                        72
#define IDM_RANDOMIZE                   73
#define IDM_PAUSE                       74
#define IDM_HELP                        80
#define IDM_ABOUT                       81
#define IDM_CLEAR                       100
#define IDC_LAMBDA_PLUS                 100
#define IDD_PAINT                       100
#define ID_OLDTEXT                      100
#define IDM_SAVE_ALL                    101
#define IDC_LAMBDA_MINUS                101
#define IDM_16                          101
#define IDC_SPINLAMBDA                  101
#define IDC_SPIN_ANALOG_SPACESTEP       101
#define IDC_SPIN_ELECTRIC_CAP           101
#define ID_NEWTEXT                      101
#define ID_SPEED                        101
#define IDM_SAVE_INDIVIDUAL             102
#define IDC_HORZPARAM                   102
#define ACC_PLUS                        102
#define IDM_256                         102
#define ID_AGAIN                        102
#define ID_MINRADIUS                    102
#define IDM_OPEN_ALL                    103
#define IDC_VERTPARAM                   103
#define ACC_MINUS                       103
#define IDM_EDITBAND                    103
#define IDM_1000                        103
#define IDC_SPINDIVERSE                 103
#define IDC_SPIN_ANALOG_VELOCITY        103
#define IDC_SPIN_ELECTRIC_FRICTION      103
#define ID_PASSWORD                     103
#define ID_MAXRADIUS                    103
#define IDM_OPEN_INDIVIDUAL             104
#define IDC_MULT_SCALE                  104
#define BAND_PLUS                       104
#define IDM_BANDPLUS                    104
#define ID_ETOLD                        104
#define ID_REFRESH                      104
#define IDM_OPENRULE_FOCUS              105
#define IDC_ADD_SCALE                   105
#define BAND_MINUS                      105
#define IDM_BANDMINUS                   105
#define IDC_SPIN_ANALOG_INTENSITY       105
#define IDC_SPIN_ELECTRIC_AMP           105
#define ID_ETNEW                        105
#define ID_SOUND                        105
#define IDM_OPENRULE_ALL                106
#define VEL_PLUS                        106
#define IDC_PUSHBUTTON1                 106
#define IDB_BITMAP1                     106
#define ID_ETAGAIN                      106
#define ID_LOCALHELP                    106
#define IDC_VERTMAX                     107
#define VEL_MINUS                       107
#define IDC_RADIOBUTTON1                107
#define IDC_SPIN_ANALOG_MAXVELOCITY     107
#define IDC_SPIN_ELECTRIC_FREQ          107
#define IDC_CURSOR1                     107
#define ID_ETPASSWORD                   107
#define ID_CONTEXTHELP                  107
#define INTENSITY_PLUS                  108
#define IDC_MONOCHROME                  108
#define ID_ICON                         108
#define ID_GLOBALHELP                   108
#define IDC_VERTMIN                     109
#define INTENSITY_MINUS                 109
#define IDC_SPIN_ANALOG_HEATCOUNT       109
#define IDC_SPIN_ELECTRIC_MASS          109
#define ID_PASSWORDHELP                 109
#define ID_PASSWORDPROTECTED            109
#define IDC_HORZMIN                     110
#define MAX_VEL_PLUS                    110
#define ID_SETPASSWORD                  110
#define IDC_HORZMAX                     111
#define MAX_VEL_MINUS                   111
#define IDC_SPIN_ANALOG_STATEGRAIN      111
#define IDC_CURSOR2                     111
#define ID_HELP                         111
#define IDC_OK                          112
#define IDCEXIT                         112
#define IDC_ENTROPY_PLUS                112
#define HEAT_COUNT_PLUS                 112
#define IDR_ACCELERATOR1                112
#define IDC_EXIT                        113
#define IDC_ENTROPY_MINUS               113
#define HEAT_COUNT_MINUS                113
#define IDC_SPIN_ANALOG_3DHEIGHT        113
#define MUTATE_BREED                    114
#define SPRING_PLUS                     114
#define IDC_RAMP                        114
#define STRIPESEED                      115
#define SPRING_MINUS                    115
#define IDC_BREED_PLUS                  116
#define FRICTION_PLUS                   116
#define IDB_BITMAP2                     116
#define IDC_BREED_MINUS                 117
#define FRICTION_MINUS                  117
#define IDC_FAIL_PLUS                   118
#define DRIVER_AMP_PLUS                 118
#define IDB_BITMAP3                     118
#define IDC_FAIL_MINUS                  119
#define DRIVER_AMP_MINUS                119
#define IDR_MENU1                       119
#define DRIVER_FREQ_PLUS                120
#define DRIVER_FREQ_MINUS               121
#define MASS_PLUS                       122
#define IDI_ICON1                       122
#define MASS_MINUS                      123
#define CHUNK_MINUS                     124
#define CHUNK_PLUS                      125
#define VARIANCE_PLUS                   126
#define VARIANCE_MINUS                  127
#define IDC_CATYPE                      130
#define IDC_EVOLVE                      131
#define IDC_GENERATOR                   134
#define IDC_DX_LOCK                     135
#define IDC_ALL                         140
#define IDM_ALL                         140
#define IDC_FOCUS                       141
#define IDM_FOCUS                       141
#define MAX_VEL                         158
#define CUR_PICK                        160
#define CUR_ZAP                         161
#define CUR_COPY                        162
#define CUR_TOUCH                       163
#define CUR_GENERATOR                   165
#define INTENSITY                       170
#define BREEDING_STEPS                  180
#define FAILSTRIPE                      182
#define SCORE                           185
#define STRIPEKILL                      186
#define TARGET_ENTROPY                  190
#define ENTROPY_SCORE                   191
#define ENTROPY                         192
#define IDC_RADIUSSTATES                195
#define TOOLBARBMP                      200
#define IDD_PROGICON                    200
#define IDC_SCORE_PLUS                  200
#define TOOLBAREXTENDED                 201
#define SPACE_STEP_NEW                  201
#define SPRING_NEW                      201
#define NUM_CAS                         201
#define TARGET_LAMBDA_NEW               201
#define IDC_SCORE_MINUS                 201
#define VELOCITY_NEW                    202
#define FRICTION_NEW                    202
#define VARIANCE_NEW                    202
#define INTENSITY_NEW                   203
#define DRIVER_AMP_NEW                  203
#define MAX_VEL_NEW                     204
#define DRIVER_FREQ_NEW                 204
#define HEAT_COUNT_NEW                  205
#define MASS_NEW                        205
#define CHUNK_NEW                       206
#define IDC_BREED_CYCLE                 210
#define TYPE                            220
#define IDC_STATES                      221
#define IDC_RADIUS                      222
#define IDM_EXP                         253
#define CHK_DX_LOCK                     301
#define IDM_FOURIER                     350
#define IDC_FOURIERALL                  351
#define IDC_FOURIERFOCUS                352
#define IDC_FOURIERGRAPH                353
#define IDC_FOURIERSCROLL               354
#define IDC_MOVELEFT                    360
#define IDC_MOVEMOVELEFT                361
#define IDC_MOVERIGHT                   362
#define IDC_MOVEMOVERIGHT               363
#define IDC_CHANGESAMPLE                364
#define IDC_TIMESCALEHALF               370
#define IDC_TIMESCALETRUE               371
#define IDC_TIMESCALEDOUBLE             372
#define IDC_SINEONLY                    375
#define IDC_COSINEONLY                  376
#define IDC_BOTHSINECOSINE              377
#define IDC_NUMTERM                     380
#define IDC_MORETERM                    381
#define IDC_LESSTERM                    382
#define IDC_APPROXIMATE                 383
#define IDC_VIEWGRAPH                   390
#define IDC_VIEWAPPROX                  391
#define IDC_VIEWCOSINE                  392
#define IDC_VIEWSINE                    393
#define IDC_VIEWSPECTRUM                394
#define HEAT_COUNT                      400
#define RADIO_ALL                       401
#define RADIO_FOCUS                     402
#define RADIO_DOWN_VIEW                 421
#define RADIO_SCROLL_VIEW               422
#define RADIO_WIRE_VIEW                 423
#define RADIO_GRAPH_VIEW                424
#define RADIO_SPLIT_VIEW                425
#define RADIO_POINT_VIEW                426
#define RADIO_FLATCOLOR                 427
#define RADIO_JUSTDOTS                  428
#define RADIO_POLYLINES                 429
#define RADIO_POLYSLICES                430
#define RADIO_SIMPLEMESH                431
#define RADIO_COLORMESH                 432
#define RADIO_GRAYDEPTH                 433
#define RADIO_ROUGHMESH                 434
#define RADIO_SHADED                    435
#define RADIO_HIDEDOTS                  436
#define RADIO_STEREO                    437
#define RADIO_OPENGL                    438
#define RADIO_BOTH_SHOW                 441
#define RADIO_ODD_SHOW                  442
#define RADIO_EVEN_SHOW                 443
#define RADIO_SHOW_CHARGE               461
#define RADIO_SHOW_CURRENT              462
#define BUTT_MUTATE                     501
#define BUTT_SYM                        501
#define BUTT_COPYMUTATE                 502
#define BUTT_REVERSE                    502
#define BUTT_BREED                      503
#define LAMBDA_TYPE                     505
#define IDC_CBWORLD                     550
#define IDC_CBCOLOR                     551
#define IDC_CBVIEW                      552
#define IDC_CBDIGITAL                   553
#define IDC_CBANALOG                    554
#define IDC_CBELECTRIC                  555
#define IDC_CBBREED                     556
#define IDC_CBCLONE                     557
#define IDC_CBFOURIER                   558
#define IDC_CBEXP                       559
#define IDC_CBCLOSE                     560
#define RADIUSSTATES_NEW                601
#define IDC_MUTATE_PLUS                 625
#define IDC_MUTATE_MINUS                626
#define IDC_MUTATION                    627
#define IDC_DOWN_VIEW                   648
#define IDC_SCROLL_VIEW                 649
#define IDC_WIRE_VIEW                   650
#define IDC_GRAPH_VIEW                  651
#define IDC_SPLIT_VIEW                  652
#define IDC_POINT_GRAPH                 653
#define IDC_2D_VIEW                     654
#define IDC_DISPLAY                     655
#define IDC_DISPLAY2                    656
#define IDC_DISPLAY3                    657
#define IDC_ALLOW_1D_RULES              700
#define IDC_ALLOW_2D_RULES              701
#define IDC_ALLOW_BOTH_RULES            702
#define IDM_OPEN_DLL                    705
#define SHOW_CHARGE                     751
#define SHOW_CURRENT                    752
#define IDC_DIGITAL                     800
#define SPACE_STEP_TYPE                 801
#define IDC_ANALOG                      801
#define TIME_STEP_TYPE                  802
#define IDC_DIGITALANALOG               802
#define MAX_INTENSITY_TYPE              803
#define MAX_VELOCITY_TYPE               804
#define HEAT_INC_TYPE                   805
#define CHUNK_TYPE                      806
#define NONLINEARITY1_TYPE              807
#define NONLINEARITY2_TYPE              808
#define SPRING_TYPE                     809
#define FRICTION_TYPE                   810
#define DRIVER_AMP_TYPE                 811
#define DRIVER_FREQ_TYPE                812
#define MASS_TYPE                       813
#define VARIANCE_TYPE                   814
#define MAX_VALPERCENT_TYPE             815
#define _3D_HEIGHT                      815
#define COL_DEFAULT                     845
#define SC_UPDATE                       900
#define IDC_SPLIT                       900
#define IDC_SCROLL                      901
#define IDC_SPLITSCROLL                 902
#define IDM_NUMBAND                     999
#define IDC_SPINBANDCOUNT               1000
#define IDC_SPIN_FOURIER_TERMS          1000
#define IDC_SPIN_BREED_BREED            1000
#define IDC_CATYPE_WORLD                1001
#define IDC_SPIN_BREED_FAIL             1008
#define IDC_SPIN_BREED_GOAL             1009
#define IDC_SPIN_BREED_SCORE            1010
#define IDC_SPIN_BREED_MUTATE           1011
#define RADIO_VIEW_ONE                  1012
#define RADIO_VIEW_FOUR                 1013
#define RADIO_VIEW_NINE                 1014
#define IDC_BUTTON2                     1022
#define IDC_GENERATORS_GEN_CUR          1022
#define IDC_OPENGL_ORIENT               1022
#define IDC_SEED_CAPOW                  1022
#define IDC_RESET                       1022
#define IDC_BUTTON3                     1023
#define IDC_OPENGL_HEIGHT               1023
#define IDC_RANDOMIZE_EVERYTHING        1023
#define IDC_SEED_HALFMAX                1023
#define IDC_BUTTON4                     1024
#define IDC_OPENGL_ZOOM                 1024
#define IDC_PROFILE_SAVE                1024
#define IDC_OPENGL_PAN                  1025
#define IDC_BUTTON5                     1026
#define IDC_OPENGL_FLY                  1026
#define IDC_EDIT1                       1028
#define IDC_NUMBAND                     1028
#define IDC_BREEDING_STEPS              1028
#define IDC_TIMER                       1028
#define IDC_EDIT2                       1029
#define IDC_FAILSTRIPE                  1029
#define IDC_EDIT3                       1030
#define IDC_TARGET_ENTROPY              1030
#define IDC_BUTTON7                     1032
#define IDC_EDIT4                       1033
#define IDC_CHECK1                      1043
#define IDC_OPENGL_FLY_SHOW             1043
#define IDC_ONE_CA                      1043
#define IDC_CHECK2                      1046
#define IDC_OPENGL_GLASSES              1046
#define IDC_FOUR_CA                     1046
#define IDC_CHECK3                      1047
#define IDC_OPENGL_ANTIALIASED          1047
#define IDC_NINE_CA                     1047
#define IDC_CHECK4                      1050
#define IDC_ALLOW_3D_VIEW               1050
#define IDC_OPENGL_GLSLEEP              1050
#define IDC_LOAD_USER_RULE              1056
#define IDC_RADIO1                      1057
#define IDC_FOURIER_SLIDER              1057
#define IDC_ALLVIEW                     1057
#define IDC_RADIO2                      1058
#define IDC_FOURIERAPPLY                1058
#define IDC_CHECK5                      1059
#define IDC_ALLOW_RANDOM_COLOR          1059
#define IDC_SPIN2                       1061
#define IDC_SPIN3                       1062
#define IDC_SPIN4                       1063
#define IDC_OPENGL_TEMPWIDTH            1065
#define IDC_OPENGL_TEMPHEIGHT           1066
#define IDC_BUTTON1                     1067
#define IDC_ZEROSEED                    1067
#define IDC_GENERATORS_PICK_CUR         1067
#define IDC_RANDOMIZE                   1067
#define BUTT_COPY                       1067
#define IDC_CURRENT_ENTROPY             1069
#define IDC_GENERATORS_REMOVE_INDEX_I   1070
#define IDC_GENERATORS_INDEX            1071
#define IDC_DING                        1078
#define ID_CANCEL                       1080
#define IDC_VARYCOUNT                   1089
#define IDC_PROFILE_FILE                1093
#define IDC_FLAT_3D_VIEW                1094
#define IDC_BOTH_3D_VIEW                1095
#define MAX_VALPERCENT_INC              1110
#define MAX_VALPERCENT_NEW              1111
#define MAX_VALPERCENT_DEC              1112
#define MAX_VALPERCENT_MINUS            1124
#define MAX_VALPERCENT_PLUS             1125
#define CBPIC_WORLDU                    1550
#define CBPIC_COLORU                    1551
#define CBPIC_VIEWU                     1552
#define CBPIC_DIGU                      1553
#define CBPIC_ANAU                      1554
#define CBPIC_ELECU                     1555
#define CBPIC_BREEDU                    1556
#define CBPIC_CLONEU                    1557
#define CBPIC_FOURIERU                  1558
#define CBPIC_EXPU                      1559
#define CBPIC_CLOSEU                    1560
#define ID_VERYSLOW                     1700
#define ID_SLOW                         1701
#define ID_MEDIUM                       1702
#define ID_FAST                         1703
#define ID_FASTEST                      1704
#define BOTH_SHOW_BUTT                  1990
#define ODD_SHOW_BUTT                   1991
#define EVEN_SHOW_BUTT                  1992
#define CURRENT_ENTROPY                 2001
#define IDM_SAVE_ALL_WITH_CELLS         2101
#define IDM_SAVE_INDIVIDUAL_WITH_CELLS  2102
#define IDC_AUTORANDOMIZE_OFF           3000
#define IDC_AUTORANDOMIZE_ON            3001
#define CBPIC_WORLDD                    3550
#define CBPIC_COLORD                    3551
#define CBPIC_VIEWD                     3552
#define CBPIC_DIGD                      3553
#define CBPIC_ANAD                      3554
#define CBPIC_ELECD                     3555
#define CBPIC_BREEDD                    3556
#define CBPIC_CLONED                    3557
#define CBPIC_FOURIERD                  3558
#define CBPIC_EXPD                      3559
#define CBPIC_CLOSED                    3560
#define IDC_LIVEEDGE                    4004
#define IDC_RANDOMTOUCH                 5555
#define COL_RAND                        5555
#define IDC_OPENGL_ZOOM_IN              6001
#define IDC_OPENGL_ZOOM_OUT             6002
#define IDC_OPENGL_GRAPHTYPES           6003
#define IDC_OPENGL_MATERIAL             6004
#define IDC_OPENGL_PAN_UP               6005
#define IDC_OPENGL_PAN_DOWN             6006
#define IDC_OPENGL_PAN_LEFT             6007
#define IDC_OPENGL_PAN_RIGHT            6008
#define IDC_OPENGL_RESET                6012
#define IDC_OPENGL_FLAT                 6014
#define IDC_OPENGL_HALFRES              6015
#define IDC_OPENGL_SHOW_GENERATORS      6016
#define IDC_OPENGL_ZERO_PLANE           6017
#define IDC_OPENGL_MAX_PLANE            6018
#define IDC_OPENGL_SPIN                 6019
#define IDC_OPENGL_PAUSE                6020
#define IDC_OPENGL_SURFACE              6021
#define IDC_OPENGL_RESOLUTION           6022
#define IDC_OPENGL_TO_VRML              6023
#define IDC_OPENGL_FLIP_TYPE            6024
#define IDC_OPENGL_SPIN2                6025
#define IDC_OPENGL_MOUSE_CA             6050
#define IDC_OPENGL_MOUSE_LIGHT          6051
#define IDC_OPENGL_MOUSE_PAN            6052
#define IDC_OPENGL_MOUSE_POINT          6053
#define IDC_OPENGL_MOUSE_ZOOM           6054
#define IDC_OPENGL_MOUSE_HEIGHT         6055
#define IDC_OPENGL_MOUSE_FLY            6056
#define CAPOWGL_FLAT                    6100
#define CAPOWGL_DOTS                    6101
#define CAPOWGL_LINES                   6102
#define CAPOWGL_SHADED                  6103
#define IDC_GENERATORS_CLEAR            7000
#define IDC_GENERATORS_SPIN_OMEGA       7001
#define IDC_GENERATORS_OMEGA            7002
#define IDC_GENERATORS_LIST1            7003
#define IDC_GENERATORS_AMP              7004
#define IDC_GENERATORS_SPIN_AMP         7005
#define IDC_GENERATORS_PHASE            7006
#define IDC_GENERATORS_SPIN_PHASE       7007
#define IDM_ANALOG                      7716
#define IDM_ELECTRIC                    7717
#define IDM_DIGITAL                     7718
#define IDM_CELL                        7719
#define IDM_VIEW                        7720
#define IDM_WORLD                       7721
#define IDM_CLOSE                       7722
#define IDM_USERDIALOG                  7723
#define IDM_OPENGL                      7724
#define IDM_LOAD_USER_RULE              7725
#define IDS_MAIN_MENU                   8000
#define IDS_MAIN_MENU1                  8001
#define IDS_MAIN_MENU2                  8002
#define IDS_MAIN_MENU3                  8003
#define IDS_MAIN_MENU4                  8004
#define IDS_MAIN_MENU5                  8005
#define IDS_FILE_MENU                   8100
#define IDS_FILE_MENU1                  8101
#define IDS_TOOLS_MENU                  8500
#define IDS_OPEN                        8500
#define IDS_TOOLS_MENU1                 8501
#define IDS_TOOLS_MENU2                 8502
#define IDS_PAUSE                       8502
#define IDS_TOOLS_MENU3                 8503
#define IDS_SPEED                       8503
#define IDS_TOOLS_MENU4                 8504
#define IDC_INFO11MIN                   9001
#define IDC_INFO12MIN                   9002
#define IDC_INFO13MIN                   9003
#define IDC_INFO21MIN                   9004
#define IDC_INFO22MIN                   9005
#define IDC_INFO23MIN                   9006
#define IDC_INFO31MIN                   9007
#define IDC_INFO32MIN                   9008
#define IDC_INFO33MIN                   9009
#define IDC_INFO11MAX                   9101
#define IDC_INFO12MAX                   9102
#define IDC_INFO13MAX                   9103
#define IDC_INFO21MAX                   9104
#define IDC_INFO22MAX                   9105
#define IDC_INFO23MAX                   9106
#define IDC_INFO31MAX                   9107
#define IDC_INFO32MAX                   9108
#define IDC_INFO33MAX                   9109
#define IDC_ZERO                        10000
#define IDC_FIXED                       10001
#define IDC_WRAP                        10002
#define IDC_FREE                        10003
#define IDC_ABSORB                      10004
#define SPRING_INC                      10100
#define FRICTION_INC                    10300
#define DRIVER_AMP_INC                  10500
#define DRIVER_FREQ_INC                 10700
#define MASS_INC                        10900
#define IDM_CAPTURE                     40002
#define IDM_CAPTURE_SAVE                40003
#define IDM_SHOW_STATUS                 40004
#define IDM_SHOW_TOOLBAR                40005
#define IDM_GENERATORS                  40006
#define IDM_COMPRESS                    40007
#define IDM_LOADRULEFOCUS               40008
#define IDM_LOADRULEALL                 40009
#define IDM_CHANGEALL                   40010
#define IDM_CHANGEFOCUS                 40011
#define IDM_CHANGEALLMENU               40012
#define IDM_CHANGEFOCUSMENU             40013
#define IDM_OLD                         40014
#define IDM_OLDTOOLBAR                  40014
#define IDC_TB_COMBOBOX                 40015
#define IDM_NEWTOOLBAR                  40015
#define IDM_SHOW_PROPERTIES             40016
#define IDM_TEST                        40018
#define IDM_VIEW_MENU                   40019
#define IDM_CATYPE_MENU                 40020
#define IDM_SEED_MENU                   40021
#define IDM_SWAP                        40022
#define IDC_SAVE_FOCUS_CA               40023
#define IDC_SAVE_ALL_CAS                40024
#define IDC_SAVE_PARAMETERS_ONLY        40025
#define IDC_SAVE_PARAMETERS_AND_IMAGE   40026
#define IDC_FILE_COMPRESSION            40027
#define IDM_FILE_SAVE                   40028
#define IDM_OPEN                        40029
#define ID_FILE_SCREENSAVER             40030
#define IDM_CONFIGURE                   40031
#define SETCURSEL                       40032
#define IDC_ALLOW_DIGITALVAL            50004
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40037
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           135
#endif
#endif
